project( vgui_controls C CXX )

set( VGUI_CONTROLS_DIR ${CMAKE_CURRENT_LIST_DIR} )
set( SOURCE_FILES
	# Private Source files
	"${VGUI_CONTROLS_DIR}/AnalogBar.cpp"
	"${VGUI_CONTROLS_DIR}/AnimatingImagePanel.cpp"
	"${VGUI_CONTROLS_DIR}/AnimationController.cpp"
	"${VGUI_CONTROLS_DIR}/BitmapImagePanel.cpp"
	"${VGUI_CONTROLS_DIR}/BuildFactoryHelper.cpp"
	"${VGUI_CONTROLS_DIR}/BuildGroup.cpp"
	"${VGUI_CONTROLS_DIR}/BuildModeDialog.cpp"
	"${VGUI_CONTROLS_DIR}/Button.cpp"
	"${VGUI_CONTROLS_DIR}/CheckButton.cpp"
	"${VGUI_CONTROLS_DIR}/CheckButtonList.cpp"
	"${VGUI_CONTROLS_DIR}/CircularProgressBar.cpp"
	"${VGUI_CONTROLS_DIR}/ComboBox.cpp"
	"${VGUI_CONTROLS_DIR}/consoledialog.cpp"
	"${VGUI_CONTROLS_DIR}/ControllerMap.cpp"
	"${VGUI_CONTROLS_DIR}/controls.cpp"
	"${VGUI_CONTROLS_DIR}/cvartogglecheckbutton.cpp"
	"${VGUI_CONTROLS_DIR}/DirectorySelectDialog.cpp"
	"${VGUI_CONTROLS_DIR}/Divider.cpp"
	"${VGUI_CONTROLS_DIR}/EditablePanel.cpp"
	"${VGUI_CONTROLS_DIR}/ExpandButton.cpp"
	"${VGUI_CONTROLS_DIR}/FileOpenDialog.cpp"
	"${VGUI_CONTROLS_DIR}/FileOpenStateMachine.cpp"
	"${VGUI_CONTROLS_DIR}/FocusNavGroup.cpp"
	"${VGUI_CONTROLS_DIR}/Frame.cpp"
	"${VGUI_CONTROLS_DIR}/GraphPanel.cpp"
	"${VGUI_CONTROLS_DIR}/HTML.cpp"
	"${VGUI_CONTROLS_DIR}/Image.cpp"
	"${VGUI_CONTROLS_DIR}/ImageList.cpp"
	"${VGUI_CONTROLS_DIR}/ImagePanel.cpp"
	"${VGUI_CONTROLS_DIR}/InputDialog.cpp"
	"${VGUI_CONTROLS_DIR}/KeyBindingHelpDialog.cpp"
	"${VGUI_CONTROLS_DIR}/KeyBoardEditorDialog.cpp"
	"${VGUI_CONTROLS_DIR}/KeyRepeat.cpp"
	"${VGUI_CONTROLS_DIR}/Label.cpp"
	"${VGUI_CONTROLS_DIR}/ListPanel.cpp"
	"${VGUI_CONTROLS_DIR}/ListViewPanel.cpp"
	"${VGUI_CONTROLS_DIR}/Menu.cpp"
	"${VGUI_CONTROLS_DIR}/MenuBar.cpp"
	"${VGUI_CONTROLS_DIR}/MenuButton.cpp"
	"${VGUI_CONTROLS_DIR}/MenuItem.cpp"
	"${VGUI_CONTROLS_DIR}/MessageBox.cpp"
	"${VGUI_CONTROLS_DIR}/MessageDialog.cpp"
	"${VGUI_CONTROLS_DIR}/Panel.cpp"
	"${VGUI_CONTROLS_DIR}/PanelListPanel.cpp"
	"${VGUI_CONTROLS_DIR}/PerforceFileExplorer.cpp"
	"${VGUI_CONTROLS_DIR}/PerforceFileList.cpp"
	"${VGUI_CONTROLS_DIR}/perforcefilelistframe.cpp"
	"${VGUI_CONTROLS_DIR}/ProgressBar.cpp"
	"${VGUI_CONTROLS_DIR}/ProgressBox.cpp"
	"${VGUI_CONTROLS_DIR}/PropertyDialog.cpp"
	"${VGUI_CONTROLS_DIR}/PropertyPage.cpp"
	"${VGUI_CONTROLS_DIR}/PropertySheet.cpp"
	"${VGUI_CONTROLS_DIR}/QueryBox.cpp"
	"${VGUI_CONTROLS_DIR}/RadioButton.cpp"
	"${VGUI_CONTROLS_DIR}/RichText.cpp"
	"${VGUI_CONTROLS_DIR}/RotatingProgressBar.cpp"
	"${VGUI_CONTROLS_DIR}/savedocumentquery.cpp"
	"${VGUI_CONTROLS_DIR}/ScalableImagePanel.cpp"
	"${VGUI_CONTROLS_DIR}/ScrollableEditablePanel.cpp"
	"${VGUI_CONTROLS_DIR}/ScrollBar.cpp"
	"${VGUI_CONTROLS_DIR}/ScrollBarSlider.cpp"
	"${VGUI_CONTROLS_DIR}/SectionedListPanel.cpp"
	"${VGUI_CONTROLS_DIR}/Slider.cpp"
	"${VGUI_CONTROLS_DIR}/Splitter.cpp"
	"${VGUI_CONTROLS_DIR}/subrectimage.cpp"
	"${VGUI_CONTROLS_DIR}/TextEntry.cpp"
	"${VGUI_CONTROLS_DIR}/TextImage.cpp"
	"${VGUI_CONTROLS_DIR}/ToggleButton.cpp"
	"${VGUI_CONTROLS_DIR}/Tooltip.cpp"
	"${VGUI_CONTROLS_DIR}/ToolWindow.cpp"
	"${VGUI_CONTROLS_DIR}/TreeView.cpp"
	"${VGUI_CONTROLS_DIR}/TreeViewListControl.cpp"
	"${VGUI_CONTROLS_DIR}/URLLabel.cpp"
	"${VGUI_CONTROLS_DIR}/WizardPanel.cpp"
	"${VGUI_CONTROLS_DIR}/WizardSubPanel.cpp"
	"${SRC_DIR}/vgui2/src/vgui_key_translation.cpp"

	# Private Header files

	# Public Source files
	"${SRC_DIR}/public/filesystem_helpers.cpp"

	# Public Header files
	"${SRC_DIR}/public/vgui_controls/AnalogBar.h"
	"${SRC_DIR}/public/vgui_controls/AnimatingImagePanel.h"
	"${SRC_DIR}/public/vgui_controls/AnimationController.h"
	"${SRC_DIR}/public/vgui_controls/BitmapImagePanel.h"
	"${SRC_DIR}/public/vgui_controls/BuildGroup.h"
	"${SRC_DIR}/public/vgui_controls/BuildModeDialog.h"
	"${SRC_DIR}/public/vgui_controls/Button.h"
	"${SRC_DIR}/public/vgui_controls/CheckButton.h"
	"${SRC_DIR}/public/vgui_controls/CheckButtonList.h"
	"${SRC_DIR}/public/vgui_controls/CircularProgressBar.h"
	"${SRC_DIR}/public/Color.h"
	"${SRC_DIR}/public/vgui_controls/ComboBox.h"
	"${SRC_DIR}/public/vgui_controls/consoledialog.h"
	"${SRC_DIR}/public/vgui_controls/ControllerMap.h"
	"${SRC_DIR}/public/vgui_controls/Controls.h"
	"${SRC_DIR}/public/vgui_controls/cvartogglecheckbutton.h"
	"${SRC_DIR}/public/vgui_controls/DialogManager.h"
	"${SRC_DIR}/public/vgui_controls/DirectorySelectDialog.h"
	"${SRC_DIR}/public/vgui_controls/Divider.h"
	"${SRC_DIR}/public/vgui_controls/EditablePanel.h"
	"${SRC_DIR}/public/vgui_controls/ExpandButton.h"
	"${SRC_DIR}/public/vgui_controls/FileOpenDialog.h"
	"${SRC_DIR}/public/vgui_controls/FileOpenStateMachine.h"
	"${SRC_DIR}/public/filesystem.h"
	"${SRC_DIR}/public/filesystem_helpers.h"
	"${SRC_DIR}/public/vgui_controls/FocusNavGroup.h"
	"${SRC_DIR}/public/vgui_controls/Frame.h"
	"${SRC_DIR}/public/vgui_controls/GraphPanel.h"
	"${SRC_DIR}/public/vgui_controls/HTML.h"
	"${SRC_DIR}/public/vgui_controls/Image.h"
	"${SRC_DIR}/public/vgui_controls/ImageList.h"
	"${SRC_DIR}/public/vgui_controls/ImagePanel.h"
	"${SRC_DIR}/public/vgui_controls/InputDialog.h"
	"${SRC_DIR}/public/tier1/interface.h"
	"${SRC_DIR}/public/vgui_controls/KeyBindingHelpDialog.h"
	"${SRC_DIR}/public/vgui_controls/KeyBindingMap.h"
	"${SRC_DIR}/public/vgui_controls/KeyBoardEditorDialog.h"
	"${SRC_DIR}/public/vgui_controls/KeyRepeat.h"
	"${SRC_DIR}/public/tier1/KeyValues.h"
	"${SRC_DIR}/public/vgui_controls/Label.h"
	"${SRC_DIR}/public/vgui_controls/ListPanel.h"
	"${SRC_DIR}/public/vgui_controls/ListViewPanel.h"
	"${SRC_DIR}/public/tier0/memdbgoff.h"
	"${SRC_DIR}/public/tier0/memdbgon.h"
	"${SRC_DIR}/public/tier1/mempool.h"
	"${SRC_DIR}/public/vgui_controls/Menu.h"
	"${SRC_DIR}/public/vgui_controls/MenuBar.h"
	"${SRC_DIR}/public/vgui_controls/MenuButton.h"
	"${SRC_DIR}/public/vgui_controls/MenuItem.h"
	"${SRC_DIR}/public/vgui_controls/MessageBox.h"
	"${SRC_DIR}/public/vgui_controls/MessageDialog.h"
	"${SRC_DIR}/public/vgui_controls/MessageMap.h"
	"${SRC_DIR}/public/vgui_controls/Panel.h"
	"${SRC_DIR}/public/vgui_controls/PanelAnimationVar.h"
	"${SRC_DIR}/public/vgui_controls/PanelListPanel.h"
	"${SRC_DIR}/public/vgui_controls/PerforceFileExplorer.h"
	"${SRC_DIR}/public/vgui_controls/PerforceFileList.h"
	"${SRC_DIR}/public/vgui_controls/perforcefilelistframe.h"
	"${SRC_DIR}/public/vgui_controls/PHandle.h"
	"${SRC_DIR}/public/vgui_controls/ProgressBar.h"
	"${SRC_DIR}/public/vgui_controls/ProgressBox.h"
	"${SRC_DIR}/public/vgui_controls/PropertyDialog.h"
	"${SRC_DIR}/public/vgui_controls/PropertyPage.h"
	"${SRC_DIR}/public/vgui_controls/PropertySheet.h"
	"${SRC_DIR}/public/vgui_controls/QueryBox.h"
	"${SRC_DIR}/public/vgui_controls/RadioButton.h"
	"${SRC_DIR}/public/vgui_controls/RichText.h"
	"${SRC_DIR}/public/vgui_controls/RotatingProgressBar.h"
	"${SRC_DIR}/public/vgui_controls/savedocumentquery.h"
	"${SRC_DIR}/public/vgui_controls/ScalableImagePanel.h"
	"${SRC_DIR}/public/vgui_controls/ScrollableEditablePanel.h"
	"${SRC_DIR}/public/vgui_controls/ScrollBar.h"
	"${SRC_DIR}/public/vgui_controls/ScrollBarSlider.h"
	"${SRC_DIR}/public/vgui_controls/SectionedListPanel.h"
	"${SRC_DIR}/public/vgui_controls/Slider.h"
	"${SRC_DIR}/public/vgui_controls/Splitter.h"
	"${SRC_DIR}/public/vgui_controls/subrectimage.h"
	"${SRC_DIR}/public/vgui_controls/TextEntry.h"
	"${SRC_DIR}/public/vgui_controls/TextImage.h"
	"${SRC_DIR}/public/vgui_controls/ToggleButton.h"
	"${SRC_DIR}/public/vgui_controls/Tooltip.h"
	"${SRC_DIR}/public/vgui_controls/ToolWindow.h"
	"${SRC_DIR}/public/vgui_controls/TreeView.h"
	"${SRC_DIR}/public/vgui_controls/TreeViewListControl.h"
	"${SRC_DIR}/public/vgui_controls/URLLabel.h"
	"${SRC_DIR}/public/tier1/utlmemory.h"
	"${SRC_DIR}/public/tier1/utlrbtree.h"
	"${SRC_DIR}/public/tier1/utlvector.h"
	"${SRC_DIR}/public/vgui_controls/WizardPanel.h"
	"${SRC_DIR}/public/vgui_controls/WizardSubPanel.h"
)

# Preprocessor defs
set( DEFINES )

# Platform-specific preprocessor defines
set( WIN32_DEFINES   )
set( POSIX32_DEFINES )
set( WIN64_DEFINES   )
set( POSIX64_DEFINES )
set( WINDOWS_DEFINES )
set( POSIX_DEFINES   )

add_library( vgui_controls STATIC )

# Include this to handle all the defines
include( ${CMAKESCRIPTS_DIR}/project-base.cmake )
