# Setup cmake standards
set( CMAKE_C_STANDARD 23 )
set( CMAKE_C_STANDARD_REQUIRED ON )
set( CMAKE_C_VISIBILITY_PRESET hidden )
set( CMAKE_CXX_STANDARD 23 )
set( CMAKE_CXX_STANDARD_REQUIRED ON )
set( CMAKE_CXX_VISIBILITY_PRESET hidden )
set( CMAKE_BUILD_RPATH_USE_ORIGIN 1 )
set( CMAKE_BUILD_RPATH $ORIGIN )
set( CMAKE_INSTALL_RPATH $ORIGIN )
set( CMAKE_BUILD_WITH_INSTALL_RPATH 1 )


# Setup platform-dependant/sdk options
set( IS_WINDOWS 0 )
set( IS_LINUX 0 )
set( IS_OSX 0 )
set( IS_POSIX 0 )
#set( IS_64BIT 0 )
set( IS_SOURCESDK 1 )

if ( WIN32 )
	set( IS_WINDOWS 1 )
	if ( IS_64BIT )
		set( PLATSUBDIR "/x64" )
	else ()
		set( PLATSUBDIR "/." )
	endif ()
	set( CMAKE_IMPORT_LIBRARY_SUFFIX ".lib" )
elseif ( UNIX )
	set( IS_POSIX 1 )
	if ( LINUX )
		set( IS_LINUX 1 )
		if ( IS_64BIT )
			set( PLATSUBDIR "/linux64" )
		else ()
			set( PLATSUBDIR "/linux32" )
		endif ()
	endif()
#	set( CMAKE_IMPORT_LIBRARY_SUFFIX ".a" )
endif()

option( RETAIL "Build in retail mode" OFF )
option( STAGING_ONLY "Staging only" OFF )
option( USE_TOGL "Use the `togl` translation layer" ${IS_LINUX} )

set( RAD_TELEMETRY_DISABLED ${IS_SOURCESDK} )
set( TF_BETA 0 )
set( BUILD_REPLAY 0 )
set( DEDICATED 0 )
